#include <iostream>
using namespace std;
int main()
{
	int x = -1;

	cout<<"Before try\n";
	try
	{
		throw x;
		cout<<"After throw(never executed)\n";
	}
	catch (int x)
	{
		cout<<"Exception caught\n";
	}
	cout<<"After catch(will be executed)\n";
	return 0;
}
